DentalClinic/Models/Appointment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DentalClinic.Models
{
    public class Appointment
    {
        public int Id { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy HH:mm}")]
        public DateTime StartFrom { get; set; }
        public int? CustomerId { get; set; }
        public int? DoctorId { get; set; }
        public int? NurseId { get; set; }
        public int? ProcedureId { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Doctor Doctor { get; set; }
        public virtual Nurse Nurse { get; set; }
        public virtual Procedure Procedure { get; set; }
        public string Observations { get; set; }
    }
}

DentalClinic/Controllers/APIControllers/AppointmentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Http.Description;
using AutoMapper;
using DentalClinic.DAL;
using DentalClinic.DTOS;
using DentalClinic.Models;

namespace DentalClinic.Controllers.APIControllers
{
    public class AppointmentsController : ApiController
    {
        private ClinicDbContext db = new ClinicDbContext();

        // GET: api/Appointments
        public IHttpActionResult GetAppointments()
        {
            var appointmentDtoList = new List<AppointmentDto>();
            var appointmentList = db.Appointments.ToList();

            foreach (var appointment in appointmentList)
            {
                appointmentDtoList.Add(Mapper.Map<Appointment, AppointmentDto>(appointment));
            }

            return Ok(appointmentDtoList);
        }

        // GET: api/Appointments/5
        [ResponseType(typeof(Appointment))]
        public IHttpActionResult GetAppointmentByDoctor(int id)
        {
            var appointment = db.Appointments.Where(x => x.DoctorId == id).ToList();
            if (appointment == null)
            {
                return NotFound();
            }

            return Ok(appointment);
        }

        // PUT: api/Appointments/5
        [ResponseType(typeof(void))]
        public IHttpActionResult PutAppointment(int id, Appointment appointment)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if (id != appointment.Id)
            {
                return BadRequest();
            }

            db.Entry(appointment).State = EntityState.Modified;

            try
            {
                db.SaveChanges();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!AppointmentExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return StatusCode(HttpStatusCode.NoContent);
        }

        // POST: api/Appointments
        [ResponseType(typeof(Appointment))]
        public IHttpActionResult PostAppointment(Appointment appointment)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            db.Appointments.Add(appointment);
            db.SaveChanges();

            return CreatedAtRoute("DefaultApi", new { id = appointment.Id }, appointment);
        }

        // DELETE: api/Appointments/5
        [ResponseType(typeof(Appointment))]
        public IHttpActionResult DeleteAppointment(int id)
        {
            Appointment appointment = db.Appointments.Find(id);
            if (appointment == null)
            {
                return NotFound();
            }

            db.Appointments.Remove(appointment);
            db.SaveChanges();

            return Ok(appointment);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private bool AppointmentExists(int id)
        {
            return db.Appointments.Count(e => e.Id == id) > 0;
        }
    }
}

DentalClinic/Controllers/AppointmentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using DentalClinic.DAL;
using DentalClinic.Models;
using DentalClinic.ModelView;
using Microsoft.AspNetCore.Mvc;

namespace DentalClinic.Controllers
{
    public class AppointmentController : Controller
    {
        private ClinicDbContext db = new ClinicDbContext();

        // GET: Appointment
        public System.Web.Mvc.ActionResult Index()
        {
            ViewBag.Date = "";
            var appointments = db.Appointments.Include(a => a.Customer).Include(a => a.Doctor).Include(a => a.Nurse).Include(a => a.Procedure);
            return View(appointments.ToList());
        }

        // GET: Appointment/Details/5
        public System.Web.Mvc.ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Appointment appointment = db.Appointments.Find(id);
            if (appointment == null)
            {
                return HttpNotFound();
            }
            return View(appointment);
        }

        // GET: Appointment/Create
        [System.Web.Mvc.HttpGet]
        [System.Web.Mvc.Route("Default")]
        public System.Web.Mvc.ActionResult Create()
        {
            ViewBag.CustomerId = new SelectList(db.Customers, "Id", "Name");
            ViewBag.DoctorId = new SelectList(db.Doctors, "Id", "Name");
            ViewBag.NurseId = new SelectList(db.Nurses, "Id", "Name");
            ViewBag.ProcedureId = new SelectList(db.Procedures, "Id", "Name");
            return View();
        }
        [System.Web.Mvc.Route("AutoCompleteDate")]
        public System.Web.Mvc.ActionResult CreateAutoCompleteDate([FromQuery] DateTime date,int id)
        {
            var appointment = new Appointment
            {
                StartFrom = date,
                DoctorId = id,
                CustomerId = null,
                NurseId = null,
                ProcedureId = null
                
            };

            ViewBag.CustomerId = new SelectList(db.Customers, "Id", "Name");
            ViewBag.DoctorId = new SelectList(db.Doctors, "Id", "Name");
            ViewBag.NurseId = new SelectList(db.Nurses, "Id", "Name");
            ViewBag.ProcedureId = new SelectList(db.Procedures, "Id", "Name");
            return View("Create",appointment);
        }

        // POST: Appointment/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [System.Web.Mvc.HttpPost]
        [System.Web.Mvc.Route("Default")]
        [ValidateAntiForgeryToken]
        public System.Web.Mvc.ActionResult Create([System.Web.Mvc.Bind(Include = "Id,StartFrom,CustomerId,DoctorId,NurseId,ProcedureId,Observations")] Appointment appointment)
        {
            if (ModelState.IsValid)
            {
                db.Appointments.Add(appointment);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CustomerId = new SelectList(db.Customers, "Id", "Name", appointment.CustomerId);
            ViewBag.DoctorId = new SelectList(db.Doctors, "Id", "Name", appointment.DoctorId);
            ViewBag.NurseId = new SelectList(db.Nurses, "Id", "Name", appointment.NurseId);
            ViewBag.ProcedureId = new SelectList(db.Procedures, "Id", "Name", appointment.ProcedureId);
            return View(appointment);
        }

        // GET: Appointment/Edit/5
        [System.Web.Mvc.Route("Default")]
        [System.Web.Mvc.HttpGet]
        public System.Web.Mvc.ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Appointment appointment = db.Appointments.Find(id);
            if (appointment == null)
            {
                return HttpNotFound();
            }
            
            ViewBag.CustomerId = new SelectList(db.Customers, "Id", "Name", appointment.CustomerId);
            ViewBag.DoctorId = new SelectList(db.Doctors, "Id", "Name", appointment.DoctorId);
            ViewBag.NurseId = new SelectList(db.Nurses, "Id", "Name", appointment.NurseId);
            ViewBag.ProcedureId = new SelectList(db.Procedures, "Id", "Name", appointment.ProcedureId);
            return View(appointment);
        }

        // POST: Appointment/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [System.Web.Mvc.Route("Default")]
        [System.Web.Mvc.HttpPost]
        [ValidateAntiForgeryToken]
        public System.Web.Mvc.ActionResult Edit([System.Web.Mvc.Bind(Include = "Id,StartFrom,CustomerId,DoctorId,NurseId,ProcedureId,Observations")] Appointment appointment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(appointment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CustomerId = new SelectList(db.Customers, "Id", "Name", appointment.CustomerId);
            ViewBag.DoctorId = new SelectList(db.Doctors, "Id", "Name", appointment.DoctorId);
            ViewBag.NurseId = new SelectList(db.Nurses, "Id", "Name", appointment.NurseId);
            ViewBag.ProcedureId = new SelectList(db.Procedures, "Id", "Name", appointment.ProcedureId);
            return View(appointment);
        }

        // GET: Appointment/Delete/5
        public System.Web.Mvc.ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Appointment appointment = db.Appointments.Find(id);
            if (appointment == null)
            {
                return HttpNotFound();
            }
            return View(appointment);
        }

        // POST: Appointment/Delete/5
        [System.Web.Mvc.HttpPost, System.Web.Mvc.ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public System.Web.Mvc.ActionResult DeleteConfirmed(int id)
        {
            Appointment appointment = db.Appointments.Find(id);
            db.Appointments.Remove(appointment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DentalClinic/Views/Appointment/Create.cshtml
@model DentalClinic.Models.Appointment

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm("Create","Appointment"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Appointment</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.StartFrom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartFrom, new { htmlAttributes = new { @class = "form-control", @type = "datetime-local", @id = "test" } })
                @Html.ValidationMessageFor(model => model.StartFrom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerId, "CustomerId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CustomerId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CustomerId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DoctorId, "DoctorId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DoctorId", null, htmlAttributes: new { @class = "form-control" , @id = "doctorId"})
                @Html.ValidationMessageFor(model => model.DoctorId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NurseId, "NurseId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("NurseId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.NurseId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProcedureId, "ProcedureId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ProcedureId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProcedureId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Observations, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Observations, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Observations, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>

        $(document).ready(function () {
            $('#test')[0].defaultValue = moment($('#test')[0].defaultValue).format("YYYY-MM-DDThh:mm")
            $('#doctorId').val(@Model.DoctorId)
        })
    </script>
}

DentalClinic/Views/Appointment/Delete.cshtml
@model DentalClinic.Models.Appointment

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Appointment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Customer.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customer.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Doctor.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Doctor.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nurse.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nurse.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Procedure.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Procedure.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartFrom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartFrom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Observations)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Observations)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DentalClinic/Views/Appointment/Details.cshtml
@model DentalClinic.Models.Appointment

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Appointment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Customer.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customer.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Doctor.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Doctor.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nurse.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nurse.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Procedure.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Procedure.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartFrom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartFrom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Observations)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Observations)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DentalClinic/Views/Appointment/Edit.cshtml
@model DentalClinic.Models.Appointment

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Appointment</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.StartFrom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartFrom, new { htmlAttributes = new { @class = "form-control", @type = "datetime-local", @id = "test" } })
                @Html.ValidationMessageFor(model => model.StartFrom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerId, "CustomerId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CustomerId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CustomerId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DoctorId, "DoctorId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DoctorId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DoctorId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NurseId, "NurseId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("NurseId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.NurseId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProcedureId, "ProcedureId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ProcedureId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProcedureId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Observations, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Observations, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Observations, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>

        $(document).ready(function () {
            $('#test')[0].defaultValue = moment($('#test')[0].defaultValue).format("YYYY-MM-DDTkk:mm")
        })
    </script>
}

DentalClinic/Views/Appointment/Index.cshtml
@model dynamic
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>


@*@using (Html.BeginForm("Create", "Appointment", FormMethod.Get))
{
    <div class="">
        <button type="submit" class="btn btn-primary">Add New Appointment</button>
    </div>
    <br>
}*@

<select id="doctors"></select>

<div id="calender"></div>

<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title"><span id="eventTitle"></span></h4>
            </div>
            <div class="modal-body">
                <button id="btnDelete" class="btn btn-default btn-sm pull-right">
                    <span class="glyphicon glyphicon-remove"></span> Remove
                </button>
                <button id="btnEdit" class="btn btn-default btn-sm pull-right" style="margin-right:5px;">
                    <span class="glyphicon glyphicon-pencil"></span> Edit
                </button>
                <p id="pDetails"></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<div id="myModalSave" class="modal fade" role="dialog">
    <div class="container">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Save Event</h4>
                </div>
                <div class="modal-body">
                    <form class="form-horizontal">
                        <input type="hidden" id="hdEventID" value="0" />

                        <div class="form-group">
                            <label>Customer</label>
                            <input type="text" id="Customer" class="form-control" />
                        </div>

                        <div class="form-group">
                            <label>Doctor</label>
                            <input type="text" id="Doctor" class="form-control" />
                        </div>

                        <div class="form-group">
                            <label>Nurse</label>
                            <input type="text" id="Nurse" class="form-control" />
                        </div>

                        <div class="form-group">
                            <label>Procedure</label>
                            <input type="text" id="Procedure" class="form-control" />
                        </div>

                        <div class="form-group">
                            <label>Start</label>
                            <input type="text" id="txtStart" class="form-control" />
                        </div>

                        <button type="button" id="btnSave" class="btn btn-success">Save</button>
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<link href="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.4.0/fullcalendar.min.css" rel="stylesheet" />
<link href="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.4.0/fullcalendar.print.css" rel="stylesheet" media="print" />
<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css" rel="stylesheet" />

@section Scripts{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>

    <script src="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.4.0/fullcalendar.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>


    <script>
        $(document).ready(function () {
            var url = "/api/appointments"
            var doctorId = 0;

            $.ajax({
                type: "GET",
                url: "/api/Doctors",
                success: function (data) {
                    var s = '<option value="-1">Please Select a Doctor</option>';
                    for (var i = 0; i < data.length; i++) {
                        s += '<option value="' + data[i].Id + '">' + data[i].Name + '</option>';
                    }
                    $("#doctors").html(s);
                }
            });

            $('select[id="doctors"]').change(function () {

                url = "/api/appointments/" + this.value
                doctorId = this.value
                console.log(url)
                FetchEventAndRenderCalendar(url)

            })


            var events = [];
            var selectedEvent = null;
            FetchEventAndRenderCalendar(url);

            function FetchEventAndRenderCalendar(urlValue) {
                var events = [];
                $.ajax({
                    type: "GET",
                    url: urlValue,
                    success: function (data) {
                        $.each(data, function (i, appointment) {
                            events.push({
                                eventID: appointment.Id,
                                title: appointment.Customer.Name,
                                description: appointment.Procedure.Name + "\n" + appointment.Doctor.Name + "-" + appointment.Nurse.Name,
                                start: moment(appointment.StartFrom),
                                end: moment(appointment.StartFrom + appointment.Procedure.Duration),
                                allDay: false
                            });
                           
                        })
                        console.log(events)
                        GenerateCalender(events);
                    },
                    error: function (error) {
                        alert('failed');
                    }
                })
            }


            function GenerateCalender(events) {
                $('#calender').fullCalendar('destroy');
                $('#calender').fullCalendar({
                    contentHeight: 600,
                    defaultDate: new Date(),
                    timeFormat: 'h:mm a',
                    header: {
                        left: 'prev,next today',
                        center: 'title',
                        right: 'month,basicWeek,basicDay'
                    },
                    eventLimit: true,
                    eventColor: '#0a90c9',
                    events: events,
                    eventClick: function (calEvent, jsEvent, view) {
                        selectedEvent = calEvent;
                        $('#myModal #eventTitle').text(calEvent.title);
                        var $description = $('<div/>');
                        $description.append($('<p/>').html('<b>Start:</b>' + calEvent.start.format("YYYY-MM-DDTkk:mm")));
                        if (calEvent.end != null) {
                            $description.append($('<p/>').html('<b>End:</b>' + calEvent.end.format("YYYY-MM-DDTkk:mm")));
                        }
                        $description.append($('<p/>').html('<b>Description:</b>' + calEvent.description));
                        $('#myModal #pDetails').empty().html($description);
                        $('#myModal').modal();
                    },
                    selectable: true,
                    select: function (start, end) {
                        var dateString = start._d.getFullYear() + "-" + start._d.getMonth() + "-" + start._d.getDate();
                        console.log(dateString)
                        console.log(start._d)
                        date = Date.parse(dateString)
                        window.location = "/Appointment/CreateAutoCompleteDate?date=" + dateString + "&id=" + doctorId

                    },
                    editable: true,
                })
            }

            $('#btnEdit').click(function () {
                window.location = "/Appointment/Edit/" + selectedEvent.eventID;
            })
            $('#btnDelete').click(function () {
                if (selectedEvent != null && confirm('Are you sure?')) {
                    $.ajax({
                        type: "Delete",
                        url: '/api/appointments/' + selectedEvent.eventID,
                        success: function () {
                            window.location = "/Appointment/Index/"
                        },
                        error: function () {
                            alert('Failed');
                        }
                    })
                }
            })
        })
    </script>
}